# Generated by Django 5.2.17 on 2026-09-14 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_experience_organization_alter_experience_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='ended_at',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='started_at',
        ),
    ]
