# Generated by Django 5.2.17 on 2026-09-14 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_experience_ended_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='started_at',
            field=models.DateTimeField(default='2026-01-01'),
            preserve_default=False,
        ),
    ]
